sudo: required
services:
  - docker
before_install: 
  - docker build -t shaunalbersdocker/react-test -f ./client/Dockerfile.dev
script: 
 - docker run shaunalbersdocker/react-test npm test -- -- cover 

after_success: 
  - docker build -t shaunalbersdocker/multi-client ./client
  - docker build -t shaunalbersdocker/multi-nginx ./nginx
  - docker build -t shaunalbersdocker/multi-server ./server
  - docker build -t shaunalbersdocker/multi-worker ./worker